apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
spec:
  selector:
    matchLabels:
      app: odoo-db
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo-db
        tier: backend
        role: master
    spec:
      containers:
      - name: odoo-db
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password
        resources:
          requests:
            memory: 2000Mi
        ports:
        - containerPort: 5432
