apiVersion: apps/v1
kind: Deployment
metadata:
  name:odoo-srv
spec:
  selector:
    matchLabels:
      app: odoo
      tier: odoo-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo
        tier: odoo-srv
    spec:
      containers:
      - name: odoo-srv
        image: odoo:14.0
        env:
        - name: HOST
          value: odoo-db
        - name: USER
          value: odoo
        - name: PASSWORD
          value: password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_PORT_5432_TCP_ADDR
          value: "localhost"
        - name: DB_PORT_5432_TCP_PORT
          value: "5432"
        - name: DB_ENV_POSTGRES_USER
          value: "odoo"
        - name: DB_ENV_POSTGRES_PASSWORD
          value: "1234"

        ports:
        - containerPort: 8069
