apiVersion: v1
kind: Service
metadata:
  name: odoo-svr
  labels:
    app: odoo-svr
    tier: frontend
spec:
  ports:
    - port: 8069
  selector:
    app: odoo-svr
    tier: frontend
  type: NodePort
